### ISSUE TITLE
When creating a architecture the output is truncated

### ISSUE THREAD

**Issue by pnavarro** [StackOps/python-automationclient#5]
automation --insecure architecture-create /home/pnavarro/dev/jsons/trinode_grizzly.arc

{"architecture":
    {
        "name": "trinode_grizzly",
        "roles": [
            {
                "name": "controller",
                "steps": [
                    {"1": ["grizzly.os"]},
                    {"2": ["grizzly.mysql"]},
                    {"3": ["grizzly.rabbitmq"]},
                    {"4": ["grizzly.keystone"]},
                    {"5": ["grizzly.glance"]},
                    {"6": ["grizzly.nova"]},
                    {"7": ["grizzly.quantum"]},
                    {"8": ["grizzly.cinder"]},
                    {"9": ["grizzly.apache"]},
                    {"10": ["grizzly.portal"]},
                    {"11": ["grizzly.chargeback"]}
                ]
            },
            {
                "name": "network",
                "steps": [
                    {"1": ["grizzly.os"]},
                    {"2": ["grizzly.quantum_plugins"]}
                ]
            },
            {
                "name": "compute",
                "steps": [
                    {"1": ["grizzly.os"]},
                    {"2": ["grizzly.compute"]}
                ]
            }
        ]
    }
}

OUTPUT:

+----------+-----------------------------------+
| Property |               Value               |
+----------+-----------------------------------+
|    id    |                 4                 |
|   name   |          trinode_grizzly          |
|  roles   |                 {                 |
|          |           "name": "compute",      |
|          |               "steps": [          |
|          |                     {             |
|          |                     "1": [        |
|          |                    "grizzly.os"   |
|          |                       ]           |
|          |                     },            |
|          |                     {             |
|          |                     "2": [        |
|          |                 "grizzly.compute" |
|          |                       ]           |
|          |                     }             |
|          |                   ]               |
|          |                 }                 |
+----------+-----------------------------------+

**Comment by jvalderrama** [comment]
Yes, it seems that output is truncated at the moment to print, so perhaps this behaviour can be happening in others outputs too. (Should be reviewed the utility that format this type of outputs -json outputs I mean-)

**Comment by jvalderrama** [comment]
Merged https://github.com/StackOps/python-automationclient/commit/2398ddba711bd4a4f790a4ac8b28a921b78cdf58
